services:
  web:
    image: php:8.2-apache
    container_name: green-electrum-web
    volumes:
      - ./html:/var/www/html
      - /home/umbrel/umbrel/app-data/bitcoin/data/bitcoin/.cookie:/run/bitcoin/.cookie:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:80"
    restart: unless-stopped

    # kompatible Härtung
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/apache2
      - /var/lock/apache2
    security_opt:
      - no-new-privileges:true
    pids_limit: 150
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  tor:
    image: alpine:3.20
    container_name: green-electrum-tor
    depends_on:
      - web
    volumes:
      - ./tor-data:/var/lib/tor
      - ./torrc:/torrc:ro
    command: >
      sh -c "apk add --no-cache tor &&
             tor -f /torrc"
    restart: unless-stopped
    read_only: false
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
